### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by dferraro303** [dgileadi/vscode-java-decompiler#6]
VSCode Version: 1.25.2 running on Windows 10
java version: 1.8.0_181
Installed Extension and restarted VSCode.
Opened folder with .class file. 
In the EXPLORER I right-click on the red icon next to the my.class file but no Go to Definition appears in menu.

**Comment by dgileadi** [comment]
This is because opening class files directly isn't supported, see issue #3, particularly [my last comment](https://github.com/dgileadi/vscode-java-decompiler/issues/3#issuecomment-371980305).

As a workaround, as long as the class is part of your project's classpath you should be able to open it by typing Ctrl + T, typing the class name and then selecting the class from the list of suggestions.
